### ISSUE TITLE
Screenshots of paths rather than files?

### ISSUE THREAD

**Issue by jbaldo** [percy/gatsby-plugin-percy#14]
Hi, I think this is more of a support request than an issue report.

For some reason, my Gatsby production build shows an error page / not found when viewing index.html files. For some pages, it quickly redirects / moves `index.html` out of the path and the page loads normally / screenshot looks right. But I'm running some localization for most of my pages. `/es/about/index.html`, `/en/about/index.html`, etc. And if you load those paths in the browser, the page flashes up for a second and then settles on Not Found. But the site runs and builds fine.

It could be something with redirects / my localization plugin. But I'm wondering... is there a way for Percy to take snapshots after loading a certain path rather than files? Or does that require the SDK rather than the CLI?

Thanks for any pointers! Working on an open source project here: https://github.com/openoakland/openousd-site/pull/79/files

**Comment by jbaldo** [comment]
Oh and actually you can see a hosted example here:
https://staging.openousd.org/en/
https://staging.openousd.org/en/index.html

**Comment by wwilsman** [comment]
Hey @jbaldo!

This should no longer be an issue with the latest Percy Gatsby plugin. The plugin no longer snapshots the static output directory, but instead query's GraphQL for page paths and snapshots those instead. If the queried paths don't line up for whatever reason, you can still use [new `static` config options](https://docs.percy.io/docs/cli-snapshot#static-options) to provide URL rewrites and snapshot overrides.

Check out the updated README for new installation and usage instructions!
